// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `RobotRemoteService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <StdAfx.h>
#include <RobotRemoteService.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <Ice/Object.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

namespace
{

namespace
{

namespace
{

namespace
{

const ::std::string __com__pera__base__runtime__remote__RobotRemoteService__runRobotStart_name = "runRobotStart";

const ::std::string __com__pera__base__runtime__remote__RobotRemoteService__runRobotStop_name = "runRobotStop";

}

}

}

}

}

namespace
{

const char* __com__pera__base__runtime__remote__RemoteException_name = "com::pera::base::runtime::remote::RemoteException";

struct __F__com__pera__base__runtime__remote__RemoteException : public ::IceInternal::UserExceptionFactory
{
    virtual void
    createAndThrow(const ::std::string&)
    {
        throw ::com::pera::base::runtime::remote::RemoteException();
    }
};

class __F__com__pera__base__runtime__remote__RemoteException__Init
{
public:

    __F__com__pera__base__runtime__remote__RemoteException__Init()
    {
        ::IceInternal::factoryTable->addExceptionFactory("::com::pera::base::runtime::remote::RemoteException", new __F__com__pera__base__runtime__remote__RemoteException);
    }

    ~__F__com__pera__base__runtime__remote__RemoteException__Init()
    {
        ::IceInternal::factoryTable->removeExceptionFactory("::com::pera::base::runtime::remote::RemoteException");
    }
};

const __F__com__pera__base__runtime__remote__RemoteException__Init __F__com__pera__base__runtime__remote__RemoteException__i;

}

com::pera::base::runtime::remote::RemoteException::RemoteException(const ::std::string& __ice_reason) :
    ::Ice::UserException(),
    reason(__ice_reason)
{
}

com::pera::base::runtime::remote::RemoteException::~RemoteException() throw()
{
}

::std::string
com::pera::base::runtime::remote::RemoteException::ice_name() const
{
    return __com__pera__base__runtime__remote__RemoteException_name;
}

com::pera::base::runtime::remote::RemoteException*
com::pera::base::runtime::remote::RemoteException::ice_clone() const
{
    return new RemoteException(*this);
}

void
com::pera::base::runtime::remote::RemoteException::ice_throw() const
{
    throw *this;
}

void
com::pera::base::runtime::remote::RemoteException::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice("::com::pera::base::runtime::remote::RemoteException", -1, true);
    __os->write(reason);
    __os->endWriteSlice();
}

void
com::pera::base::runtime::remote::RemoteException::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->read(reason);
    __is->endReadSlice();
}

namespace Ice
{
}
::IceProxy::Ice::Object* ::IceProxy::com::pera::base::runtime::remote::upCast(::IceProxy::com::pera::base::runtime::remote::RobotRemoteService* p) { return p; }

void
::IceProxy::com::pera::base::runtime::remote::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::com::pera::base::runtime::remote::RobotRemoteService>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::com::pera::base::runtime::remote::RobotRemoteService;
        v->__copyFrom(proxy);
    }
}

::std::string
IceProxy::com::pera::base::runtime::remote::RobotRemoteService::runRobotStart(const ::std::string& robotInfo, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __com__pera__base__runtime__remote__RobotRemoteService__runRobotStart_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__com__pera__base__runtime__remote__RobotRemoteService__runRobotStart_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::com::pera::base::runtime::remote::RobotRemoteService* __del = dynamic_cast< ::IceDelegate::com::pera::base::runtime::remote::RobotRemoteService*>(__delBase.get());
            return __del->runRobotStart(robotInfo, __ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::com::pera::base::runtime::remote::RobotRemoteService::begin_runRobotStart(const ::std::string& robotInfo, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__com__pera__base__runtime__remote__RobotRemoteService__runRobotStart_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __com__pera__base__runtime__remote__RobotRemoteService__runRobotStart_name, __del, __cookie);
    try
    {
        __result->__prepare(__com__pera__base__runtime__remote__RobotRemoteService__runRobotStart_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(robotInfo);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

::std::string
IceProxy::com::pera::base::runtime::remote::RobotRemoteService::end_runRobotStart(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __com__pera__base__runtime__remote__RobotRemoteService__runRobotStart_name);
    ::std::string __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::com::pera::base::runtime::remote::RemoteException&)
            {
                throw;
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

void
IceProxy::com::pera::base::runtime::remote::RobotRemoteService::runRobotStop(const ::std::string& taskId, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __com__pera__base__runtime__remote__RobotRemoteService__runRobotStop_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__com__pera__base__runtime__remote__RobotRemoteService__runRobotStop_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::com::pera::base::runtime::remote::RobotRemoteService* __del = dynamic_cast< ::IceDelegate::com::pera::base::runtime::remote::RobotRemoteService*>(__delBase.get());
            __del->runRobotStop(taskId, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::com::pera::base::runtime::remote::RobotRemoteService::begin_runRobotStop(const ::std::string& taskId, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__com__pera__base__runtime__remote__RobotRemoteService__runRobotStop_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __com__pera__base__runtime__remote__RobotRemoteService__runRobotStop_name, __del, __cookie);
    try
    {
        __result->__prepare(__com__pera__base__runtime__remote__RobotRemoteService__runRobotStop_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(taskId);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::com::pera::base::runtime::remote::RobotRemoteService::end_runRobotStop(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __com__pera__base__runtime__remote__RobotRemoteService__runRobotStop_name);
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::com::pera::base::runtime::remote::RemoteException&)
            {
                throw;
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        __result->__readEmptyParams();
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

const ::std::string&
IceProxy::com::pera::base::runtime::remote::RobotRemoteService::ice_staticId()
{
    return ::com::pera::base::runtime::remote::RobotRemoteService::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::com::pera::base::runtime::remote::RobotRemoteService::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::com::pera::base::runtime::remote::RobotRemoteService);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::com::pera::base::runtime::remote::RobotRemoteService::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::com::pera::base::runtime::remote::RobotRemoteService);
}

::IceProxy::Ice::Object*
IceProxy::com::pera::base::runtime::remote::RobotRemoteService::__newInstance() const
{
    return new RobotRemoteService;
}

::std::string
IceDelegateM::com::pera::base::runtime::remote::RobotRemoteService::runRobotStart(const ::std::string& robotInfo, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __com__pera__base__runtime__remote__RobotRemoteService__runRobotStart_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(robotInfo);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    ::std::string __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::com::pera::base::runtime::remote::RemoteException&)
            {
                throw;
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

void
IceDelegateM::com::pera::base::runtime::remote::RobotRemoteService::runRobotStop(const ::std::string& taskId, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __com__pera__base__runtime__remote__RobotRemoteService__runRobotStop_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(taskId);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::com::pera::base::runtime::remote::RemoteException&)
            {
                throw;
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        __og.readEmptyParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

::std::string
IceDelegateD::com::pera::base::runtime::remote::RobotRemoteService::runRobotStart(const ::std::string& robotInfo, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::std::string& __result, const ::std::string& __p_robotInfo, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_robotInfo(__p_robotInfo)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::com::pera::base::runtime::remote::RobotRemoteService* servant = dynamic_cast< ::com::pera::base::runtime::remote::RobotRemoteService*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            try
            {
                _result = servant->runRobotStart(_m_robotInfo, _current);
                return ::Ice::DispatchOK;
            }
            catch(const ::Ice::UserException& __ex)
            {
                setUserException(__ex);
                return ::Ice::DispatchUserException;
            }
        }
        
    private:
        
        ::std::string& _result;
        const ::std::string& _m_robotInfo;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __com__pera__base__runtime__remote__RobotRemoteService__runRobotStart_name, ::Ice::Normal, __context);
    ::std::string __result;
    try
    {
        _DirectI __direct(__result, robotInfo, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::com::pera::base::runtime::remote::RemoteException&)
    {
        throw;
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

void
IceDelegateD::com::pera::base::runtime::remote::RobotRemoteService::runRobotStop(const ::std::string& taskId, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::std::string& __p_taskId, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_taskId(__p_taskId)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::com::pera::base::runtime::remote::RobotRemoteService* servant = dynamic_cast< ::com::pera::base::runtime::remote::RobotRemoteService*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            try
            {
                servant->runRobotStop(_m_taskId, _current);
                return ::Ice::DispatchOK;
            }
            catch(const ::Ice::UserException& __ex)
            {
                setUserException(__ex);
                return ::Ice::DispatchUserException;
            }
        }
        
    private:
        
        const ::std::string& _m_taskId;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __com__pera__base__runtime__remote__RobotRemoteService__runRobotStop_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(taskId, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::com::pera::base::runtime::remote::RemoteException&)
    {
        throw;
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

::Ice::Object* com::pera::base::runtime::remote::upCast(::com::pera::base::runtime::remote::RobotRemoteService* p) { return p; }

namespace
{
const ::std::string __com__pera__base__runtime__remote__RobotRemoteService_ids[2] =
{
    "::Ice::Object",
    "::com::pera::base::runtime::remote::RobotRemoteService"
};

}

bool
com::pera::base::runtime::remote::RobotRemoteService::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__com__pera__base__runtime__remote__RobotRemoteService_ids, __com__pera__base__runtime__remote__RobotRemoteService_ids + 2, _s);
}

::std::vector< ::std::string>
com::pera::base::runtime::remote::RobotRemoteService::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__com__pera__base__runtime__remote__RobotRemoteService_ids[0], &__com__pera__base__runtime__remote__RobotRemoteService_ids[2]);
}

const ::std::string&
com::pera::base::runtime::remote::RobotRemoteService::ice_id(const ::Ice::Current&) const
{
    return __com__pera__base__runtime__remote__RobotRemoteService_ids[1];
}

const ::std::string&
com::pera::base::runtime::remote::RobotRemoteService::ice_staticId()
{
    return __com__pera__base__runtime__remote__RobotRemoteService_ids[1];
}

::Ice::DispatchStatus
com::pera::base::runtime::remote::RobotRemoteService::___runRobotStart(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::std::string robotInfo;
    __is->read(robotInfo);
    __inS.endReadParams();
    try
    {
        ::std::string __ret = runRobotStart(robotInfo, __current);
        ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
        __os->write(__ret);
        __inS.__endWriteParams(true);
        return ::Ice::DispatchOK;
    }
    catch(const ::com::pera::base::runtime::remote::RemoteException& __ex)
    {
        __inS.__writeUserException(__ex, ::Ice::DefaultFormat);
    }
    return ::Ice::DispatchUserException;
}

::Ice::DispatchStatus
com::pera::base::runtime::remote::RobotRemoteService::___runRobotStop(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::std::string taskId;
    __is->read(taskId);
    __inS.endReadParams();
    try
    {
        runRobotStop(taskId, __current);
        __inS.__writeEmptyParams();
        return ::Ice::DispatchOK;
    }
    catch(const ::com::pera::base::runtime::remote::RemoteException& __ex)
    {
        __inS.__writeUserException(__ex, ::Ice::DefaultFormat);
    }
    return ::Ice::DispatchUserException;
}

namespace
{
const ::std::string __com__pera__base__runtime__remote__RobotRemoteService_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "runRobotStart",
    "runRobotStop"
};

}

::Ice::DispatchStatus
com::pera::base::runtime::remote::RobotRemoteService::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__com__pera__base__runtime__remote__RobotRemoteService_all, __com__pera__base__runtime__remote__RobotRemoteService_all + 6, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __com__pera__base__runtime__remote__RobotRemoteService_all)
    {
        case 0:
        {
            return ___ice_id(in, current);
        }
        case 1:
        {
            return ___ice_ids(in, current);
        }
        case 2:
        {
            return ___ice_isA(in, current);
        }
        case 3:
        {
            return ___ice_ping(in, current);
        }
        case 4:
        {
            return ___runRobotStart(in, current);
        }
        case 5:
        {
            return ___runRobotStop(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
com::pera::base::runtime::remote::RobotRemoteService::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
com::pera::base::runtime::remote::RobotRemoteService::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
com::pera::base::runtime::remote::__patch(RobotRemoteServicePtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::com::pera::base::runtime::remote::RobotRemoteServicePtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::com::pera::base::runtime::remote::RobotRemoteService::ice_staticId(), v);
    }
}
