// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `PeraNetDiskIce.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <StdAfx.h>
#include <PeraNetDiskIce.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <Ice/Object.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

namespace
{

namespace
{

const ::std::string __Pera__NetDisk__Daemon__PeraNetDiskDaemonService__InvokeMethod_name = "InvokeMethod";

}

}

}

namespace
{

const char* __Pera__NetDisk__Daemon__InvokeException_name = "Pera::NetDisk::Daemon::InvokeException";

struct __F__Pera__NetDisk__Daemon__InvokeException : public ::IceInternal::UserExceptionFactory
{
    virtual void
    createAndThrow(const ::std::string&)
    {
        throw ::Pera::NetDisk::Daemon::InvokeException();
    }
};

class __F__Pera__NetDisk__Daemon__InvokeException__Init
{
public:

    __F__Pera__NetDisk__Daemon__InvokeException__Init()
    {
        ::IceInternal::factoryTable->addExceptionFactory("::Pera::NetDisk::Daemon::InvokeException", new __F__Pera__NetDisk__Daemon__InvokeException);
    }

    ~__F__Pera__NetDisk__Daemon__InvokeException__Init()
    {
        ::IceInternal::factoryTable->removeExceptionFactory("::Pera::NetDisk::Daemon::InvokeException");
    }
};

const __F__Pera__NetDisk__Daemon__InvokeException__Init __F__Pera__NetDisk__Daemon__InvokeException__i;

}

Pera::NetDisk::Daemon::InvokeException::InvokeException(const ::std::string& __ice_reason) :
    ::Ice::UserException(),
    reason(__ice_reason)
{
}

Pera::NetDisk::Daemon::InvokeException::~InvokeException() throw()
{
}

::std::string
Pera::NetDisk::Daemon::InvokeException::ice_name() const
{
    return __Pera__NetDisk__Daemon__InvokeException_name;
}

Pera::NetDisk::Daemon::InvokeException*
Pera::NetDisk::Daemon::InvokeException::ice_clone() const
{
    return new InvokeException(*this);
}

void
Pera::NetDisk::Daemon::InvokeException::ice_throw() const
{
    throw *this;
}

void
Pera::NetDisk::Daemon::InvokeException::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice("::Pera::NetDisk::Daemon::InvokeException", -1, true);
    __os->write(reason);
    __os->endWriteSlice();
}

void
Pera::NetDisk::Daemon::InvokeException::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->read(reason);
    __is->endReadSlice();
}

namespace Ice
{
}
::IceProxy::Ice::Object* ::IceProxy::Pera::NetDisk::Daemon::upCast(::IceProxy::Pera::NetDisk::Daemon::PeraNetDiskDaemonService* p) { return p; }

void
::IceProxy::Pera::NetDisk::Daemon::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::Pera::NetDisk::Daemon::PeraNetDiskDaemonService>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::Pera::NetDisk::Daemon::PeraNetDiskDaemonService;
        v->__copyFrom(proxy);
    }
}

::std::string
IceProxy::Pera::NetDisk::Daemon::PeraNetDiskDaemonService::InvokeMethod(const ::std::string& strMethodName, const ::std::string& strJsonIn, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __Pera__NetDisk__Daemon__PeraNetDiskDaemonService__InvokeMethod_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__Pera__NetDisk__Daemon__PeraNetDiskDaemonService__InvokeMethod_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::Pera::NetDisk::Daemon::PeraNetDiskDaemonService* __del = dynamic_cast< ::IceDelegate::Pera::NetDisk::Daemon::PeraNetDiskDaemonService*>(__delBase.get());
            return __del->InvokeMethod(strMethodName, strJsonIn, __ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::Pera::NetDisk::Daemon::PeraNetDiskDaemonService::begin_InvokeMethod(const ::std::string& strMethodName, const ::std::string& strJsonIn, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__Pera__NetDisk__Daemon__PeraNetDiskDaemonService__InvokeMethod_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __Pera__NetDisk__Daemon__PeraNetDiskDaemonService__InvokeMethod_name, __del, __cookie);
    try
    {
        __result->__prepare(__Pera__NetDisk__Daemon__PeraNetDiskDaemonService__InvokeMethod_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(strMethodName);
        __os->write(strJsonIn);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

::std::string
IceProxy::Pera::NetDisk::Daemon::PeraNetDiskDaemonService::end_InvokeMethod(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __Pera__NetDisk__Daemon__PeraNetDiskDaemonService__InvokeMethod_name);
    ::std::string __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Pera::NetDisk::Daemon::InvokeException&)
            {
                throw;
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

const ::std::string&
IceProxy::Pera::NetDisk::Daemon::PeraNetDiskDaemonService::ice_staticId()
{
    return ::Pera::NetDisk::Daemon::PeraNetDiskDaemonService::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::Pera::NetDisk::Daemon::PeraNetDiskDaemonService::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::Pera::NetDisk::Daemon::PeraNetDiskDaemonService);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::Pera::NetDisk::Daemon::PeraNetDiskDaemonService::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::Pera::NetDisk::Daemon::PeraNetDiskDaemonService);
}

::IceProxy::Ice::Object*
IceProxy::Pera::NetDisk::Daemon::PeraNetDiskDaemonService::__newInstance() const
{
    return new PeraNetDiskDaemonService;
}

::std::string
IceDelegateM::Pera::NetDisk::Daemon::PeraNetDiskDaemonService::InvokeMethod(const ::std::string& strMethodName, const ::std::string& strJsonIn, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __Pera__NetDisk__Daemon__PeraNetDiskDaemonService__InvokeMethod_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(strMethodName);
        __os->write(strJsonIn);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    ::std::string __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Pera::NetDisk::Daemon::InvokeException&)
            {
                throw;
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

::std::string
IceDelegateD::Pera::NetDisk::Daemon::PeraNetDiskDaemonService::InvokeMethod(const ::std::string& strMethodName, const ::std::string& strJsonIn, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::std::string& __result, const ::std::string& __p_strMethodName, const ::std::string& __p_strJsonIn, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_strMethodName(__p_strMethodName),
            _m_strJsonIn(__p_strJsonIn)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::Pera::NetDisk::Daemon::PeraNetDiskDaemonService* servant = dynamic_cast< ::Pera::NetDisk::Daemon::PeraNetDiskDaemonService*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            try
            {
                _result = servant->InvokeMethod(_m_strMethodName, _m_strJsonIn, _current);
                return ::Ice::DispatchOK;
            }
            catch(const ::Ice::UserException& __ex)
            {
                setUserException(__ex);
                return ::Ice::DispatchUserException;
            }
        }
        
    private:
        
        ::std::string& _result;
        const ::std::string& _m_strMethodName;
        const ::std::string& _m_strJsonIn;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __Pera__NetDisk__Daemon__PeraNetDiskDaemonService__InvokeMethod_name, ::Ice::Normal, __context);
    ::std::string __result;
    try
    {
        _DirectI __direct(__result, strMethodName, strJsonIn, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Pera::NetDisk::Daemon::InvokeException&)
    {
        throw;
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

::Ice::Object* Pera::NetDisk::Daemon::upCast(::Pera::NetDisk::Daemon::PeraNetDiskDaemonService* p) { return p; }

namespace
{
const ::std::string __Pera__NetDisk__Daemon__PeraNetDiskDaemonService_ids[2] =
{
    "::Ice::Object",
    "::Pera::NetDisk::Daemon::PeraNetDiskDaemonService"
};

}

bool
Pera::NetDisk::Daemon::PeraNetDiskDaemonService::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__Pera__NetDisk__Daemon__PeraNetDiskDaemonService_ids, __Pera__NetDisk__Daemon__PeraNetDiskDaemonService_ids + 2, _s);
}

::std::vector< ::std::string>
Pera::NetDisk::Daemon::PeraNetDiskDaemonService::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__Pera__NetDisk__Daemon__PeraNetDiskDaemonService_ids[0], &__Pera__NetDisk__Daemon__PeraNetDiskDaemonService_ids[2]);
}

const ::std::string&
Pera::NetDisk::Daemon::PeraNetDiskDaemonService::ice_id(const ::Ice::Current&) const
{
    return __Pera__NetDisk__Daemon__PeraNetDiskDaemonService_ids[1];
}

const ::std::string&
Pera::NetDisk::Daemon::PeraNetDiskDaemonService::ice_staticId()
{
    return __Pera__NetDisk__Daemon__PeraNetDiskDaemonService_ids[1];
}

::Ice::DispatchStatus
Pera::NetDisk::Daemon::PeraNetDiskDaemonService::___InvokeMethod(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::std::string strMethodName;
    ::std::string strJsonIn;
    __is->read(strMethodName);
    __is->read(strJsonIn);
    __inS.endReadParams();
    try
    {
        ::std::string __ret = InvokeMethod(strMethodName, strJsonIn, __current);
        ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
        __os->write(__ret);
        __inS.__endWriteParams(true);
        return ::Ice::DispatchOK;
    }
    catch(const ::Pera::NetDisk::Daemon::InvokeException& __ex)
    {
        __inS.__writeUserException(__ex, ::Ice::DefaultFormat);
    }
    return ::Ice::DispatchUserException;
}

namespace
{
const ::std::string __Pera__NetDisk__Daemon__PeraNetDiskDaemonService_all[] =
{
    "InvokeMethod",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

::Ice::DispatchStatus
Pera::NetDisk::Daemon::PeraNetDiskDaemonService::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__Pera__NetDisk__Daemon__PeraNetDiskDaemonService_all, __Pera__NetDisk__Daemon__PeraNetDiskDaemonService_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __Pera__NetDisk__Daemon__PeraNetDiskDaemonService_all)
    {
        case 0:
        {
            return ___InvokeMethod(in, current);
        }
        case 1:
        {
            return ___ice_id(in, current);
        }
        case 2:
        {
            return ___ice_ids(in, current);
        }
        case 3:
        {
            return ___ice_isA(in, current);
        }
        case 4:
        {
            return ___ice_ping(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
Pera::NetDisk::Daemon::PeraNetDiskDaemonService::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
Pera::NetDisk::Daemon::PeraNetDiskDaemonService::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
Pera::NetDisk::Daemon::__patch(PeraNetDiskDaemonServicePtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::Pera::NetDisk::Daemon::PeraNetDiskDaemonServicePtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::Pera::NetDisk::Daemon::PeraNetDiskDaemonService::ice_staticId(), v);
    }
}
