// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `RunTimeICEService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <StdAfx.h>
#include <RunTimeICEService.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <Ice/Object.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __FlexwareRuntimeICEService__RunTimeICEService__RunRobot_name = "RunRobot";

const ::std::string __FlexwareRuntimeICEService__RunTimeICEService__RunFPY_name = "RunFPY";

}
::IceProxy::Ice::Object* ::IceProxy::FlexwareRuntimeICEService::upCast(::IceProxy::FlexwareRuntimeICEService::RunTimeICEService* p) { return p; }

void
::IceProxy::FlexwareRuntimeICEService::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::FlexwareRuntimeICEService::RunTimeICEService>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::FlexwareRuntimeICEService::RunTimeICEService;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::FlexwareRuntimeICEService::RunTimeICEService::RunRobot(const ::std::string& args, ::Ice::Int processId, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __FlexwareRuntimeICEService__RunTimeICEService__RunRobot_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::FlexwareRuntimeICEService::RunTimeICEService* __del = dynamic_cast< ::IceDelegate::FlexwareRuntimeICEService::RunTimeICEService*>(__delBase.get());
            __del->RunRobot(args, processId, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::FlexwareRuntimeICEService::RunTimeICEService::begin_RunRobot(const ::std::string& args, ::Ice::Int processId, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __FlexwareRuntimeICEService__RunTimeICEService__RunRobot_name, __del, __cookie);
    try
    {
        __result->__prepare(__FlexwareRuntimeICEService__RunTimeICEService__RunRobot_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(args);
        __os->write(processId);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::FlexwareRuntimeICEService::RunTimeICEService::end_RunRobot(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __FlexwareRuntimeICEService__RunTimeICEService__RunRobot_name);
}

void
IceProxy::FlexwareRuntimeICEService::RunTimeICEService::RunFPY(const ::std::string& args, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __FlexwareRuntimeICEService__RunTimeICEService__RunFPY_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::FlexwareRuntimeICEService::RunTimeICEService* __del = dynamic_cast< ::IceDelegate::FlexwareRuntimeICEService::RunTimeICEService*>(__delBase.get());
            __del->RunFPY(args, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::FlexwareRuntimeICEService::RunTimeICEService::begin_RunFPY(const ::std::string& args, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __FlexwareRuntimeICEService__RunTimeICEService__RunFPY_name, __del, __cookie);
    try
    {
        __result->__prepare(__FlexwareRuntimeICEService__RunTimeICEService__RunFPY_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(args);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::FlexwareRuntimeICEService::RunTimeICEService::end_RunFPY(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __FlexwareRuntimeICEService__RunTimeICEService__RunFPY_name);
}

const ::std::string&
IceProxy::FlexwareRuntimeICEService::RunTimeICEService::ice_staticId()
{
    return ::FlexwareRuntimeICEService::RunTimeICEService::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::FlexwareRuntimeICEService::RunTimeICEService::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::FlexwareRuntimeICEService::RunTimeICEService);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::FlexwareRuntimeICEService::RunTimeICEService::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::FlexwareRuntimeICEService::RunTimeICEService);
}

::IceProxy::Ice::Object*
IceProxy::FlexwareRuntimeICEService::RunTimeICEService::__newInstance() const
{
    return new RunTimeICEService;
}

void
IceDelegateM::FlexwareRuntimeICEService::RunTimeICEService::RunRobot(const ::std::string& args, ::Ice::Int processId, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __FlexwareRuntimeICEService__RunTimeICEService__RunRobot_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(args);
        __os->write(processId);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(__og.hasResponse())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.readEmptyParams();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

void
IceDelegateM::FlexwareRuntimeICEService::RunTimeICEService::RunFPY(const ::std::string& args, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __FlexwareRuntimeICEService__RunTimeICEService__RunFPY_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(args);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(__og.hasResponse())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.readEmptyParams();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

void
IceDelegateD::FlexwareRuntimeICEService::RunTimeICEService::RunRobot(const ::std::string& args, ::Ice::Int processId, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::std::string& __p_args, ::Ice::Int __p_processId, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_args(__p_args),
            _m_processId(__p_processId)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::FlexwareRuntimeICEService::RunTimeICEService* servant = dynamic_cast< ::FlexwareRuntimeICEService::RunTimeICEService*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->RunRobot(_m_args, _m_processId, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        const ::std::string& _m_args;
        ::Ice::Int _m_processId;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __FlexwareRuntimeICEService__RunTimeICEService__RunRobot_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(args, processId, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

void
IceDelegateD::FlexwareRuntimeICEService::RunTimeICEService::RunFPY(const ::std::string& args, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::std::string& __p_args, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_args(__p_args)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::FlexwareRuntimeICEService::RunTimeICEService* servant = dynamic_cast< ::FlexwareRuntimeICEService::RunTimeICEService*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->RunFPY(_m_args, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        const ::std::string& _m_args;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __FlexwareRuntimeICEService__RunTimeICEService__RunFPY_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(args, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

::Ice::Object* FlexwareRuntimeICEService::upCast(::FlexwareRuntimeICEService::RunTimeICEService* p) { return p; }

namespace
{
const ::std::string __FlexwareRuntimeICEService__RunTimeICEService_ids[2] =
{
    "::FlexwareRuntimeICEService::RunTimeICEService",
    "::Ice::Object"
};

}

bool
FlexwareRuntimeICEService::RunTimeICEService::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__FlexwareRuntimeICEService__RunTimeICEService_ids, __FlexwareRuntimeICEService__RunTimeICEService_ids + 2, _s);
}

::std::vector< ::std::string>
FlexwareRuntimeICEService::RunTimeICEService::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__FlexwareRuntimeICEService__RunTimeICEService_ids[0], &__FlexwareRuntimeICEService__RunTimeICEService_ids[2]);
}

const ::std::string&
FlexwareRuntimeICEService::RunTimeICEService::ice_id(const ::Ice::Current&) const
{
    return __FlexwareRuntimeICEService__RunTimeICEService_ids[0];
}

const ::std::string&
FlexwareRuntimeICEService::RunTimeICEService::ice_staticId()
{
    return __FlexwareRuntimeICEService__RunTimeICEService_ids[0];
}

::Ice::DispatchStatus
FlexwareRuntimeICEService::RunTimeICEService::___RunRobot(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::std::string args;
    ::Ice::Int processId;
    __is->read(args);
    __is->read(processId);
    __inS.endReadParams();
    RunRobot(args, processId, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
FlexwareRuntimeICEService::RunTimeICEService::___RunFPY(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::std::string args;
    __is->read(args);
    __inS.endReadParams();
    RunFPY(args, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __FlexwareRuntimeICEService__RunTimeICEService_all[] =
{
    "RunFPY",
    "RunRobot",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

::Ice::DispatchStatus
FlexwareRuntimeICEService::RunTimeICEService::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__FlexwareRuntimeICEService__RunTimeICEService_all, __FlexwareRuntimeICEService__RunTimeICEService_all + 6, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __FlexwareRuntimeICEService__RunTimeICEService_all)
    {
        case 0:
        {
            return ___RunFPY(in, current);
        }
        case 1:
        {
            return ___RunRobot(in, current);
        }
        case 2:
        {
            return ___ice_id(in, current);
        }
        case 3:
        {
            return ___ice_ids(in, current);
        }
        case 4:
        {
            return ___ice_isA(in, current);
        }
        case 5:
        {
            return ___ice_ping(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
FlexwareRuntimeICEService::RunTimeICEService::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
FlexwareRuntimeICEService::RunTimeICEService::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
FlexwareRuntimeICEService::__patch(RunTimeICEServicePtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::FlexwareRuntimeICEService::RunTimeICEServicePtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::FlexwareRuntimeICEService::RunTimeICEService::ice_staticId(), v);
    }
}
