/* ERMClientServiceremoting_x002fERMClientServiceSoapBindingProxy.h
   Generated by gSOAP 2.8.17r from ERMClientService.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef ERMClientServiceremoting_x002fERMClientServiceSoapBindingProxy_H
#define ERMClientServiceremoting_x002fERMClientServiceSoapBindingProxy_H
#include "ERMClientServiceH.h"

namespace ERMClientService {

class SOAP_CMAC remoting_x002fERMClientServiceSoapBindingProxy
{ public:
	struct soap *soap;
	bool own;
	/// Endpoint URL of service 'remoting_x002fERMClientServiceSoapBindingProxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	remoting_x002fERMClientServiceSoapBindingProxy();
	/// Constructor to use/share an engine state
	remoting_x002fERMClientServiceSoapBindingProxy(struct soap*);
	/// Constructor with endpoint URL
	remoting_x002fERMClientServiceSoapBindingProxy(const char *url);
	/// Constructor with engine input+output mode control
	remoting_x002fERMClientServiceSoapBindingProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	remoting_x002fERMClientServiceSoapBindingProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	remoting_x002fERMClientServiceSoapBindingProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~remoting_x002fERMClientServiceSoapBindingProxy();
	/// Initializer used by constructors
	virtual	void remoting_x002fERMClientServiceSoapBindingProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (with soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to default
	virtual	void reset();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'dologin' (returns error code or SOAP_OK)
	virtual	int dologin(std::string ERMClientService1__dologin, std::string &ERMClientService1__dologinResponse) { return this->dologin(NULL, NULL, ERMClientService1__dologin, ERMClientService1__dologinResponse); }
	virtual	int dologin(const char *endpoint, const char *soap_action, std::string ERMClientService1__dologin, std::string &ERMClientService1__dologinResponse);

	/// Web service operation 'logout' (returns error code or SOAP_OK)
	virtual	int logout(std::string ERMClientService1__logout, std::string &ERMClientService1__logoutResponse) { return this->logout(NULL, NULL, ERMClientService1__logout, ERMClientService1__logoutResponse); }
	virtual	int logout(const char *endpoint, const char *soap_action, std::string ERMClientService1__logout, std::string &ERMClientService1__logoutResponse);

	/// Web service operation 'updateLastAccessedTime' (returns error code or SOAP_OK)
	virtual	int updateLastAccessedTime(std::string ERMClientService1__updateLastAccessedTime, std::string &ERMClientService1__updateLastAccessedTimeResponse) { return this->updateLastAccessedTime(NULL, NULL, ERMClientService1__updateLastAccessedTime, ERMClientService1__updateLastAccessedTimeResponse); }
	virtual	int updateLastAccessedTime(const char *endpoint, const char *soap_action, std::string ERMClientService1__updateLastAccessedTime, std::string &ERMClientService1__updateLastAccessedTimeResponse);

	/// Web service operation 'getUserByUserName' (returns error code or SOAP_OK)
	virtual	int getUserByUserName(std::string ERMClientService1__getUserByUserName, std::string &ERMClientService1__getUserByUserNameResponse) { return this->getUserByUserName(NULL, NULL, ERMClientService1__getUserByUserName, ERMClientService1__getUserByUserNameResponse); }
	virtual	int getUserByUserName(const char *endpoint, const char *soap_action, std::string ERMClientService1__getUserByUserName, std::string &ERMClientService1__getUserByUserNameResponse);
};

} // namespace ERMClientService

#endif
