// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `Pera601DemoClientIce.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __Pera601DemoClientIce_h__
#define __Pera601DemoClientIce_h__

#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace pera
{

namespace demo601Client
{

class PeraDemo601ClientService;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::pera::demo601Client::PeraDemo601ClientService>&);
::IceProxy::Ice::Object* upCast(::IceProxy::pera::demo601Client::PeraDemo601ClientService*);

}

}

}

namespace pera
{

namespace demo601Client
{

class PeraDemo601ClientService;
bool operator==(const PeraDemo601ClientService&, const PeraDemo601ClientService&);
bool operator<(const PeraDemo601ClientService&, const PeraDemo601ClientService&);
::Ice::Object* upCast(::pera::demo601Client::PeraDemo601ClientService*);
typedef ::IceInternal::Handle< ::pera::demo601Client::PeraDemo601ClientService> PeraDemo601ClientServicePtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::pera::demo601Client::PeraDemo601ClientService> PeraDemo601ClientServicePrx;
void __patch(PeraDemo601ClientServicePtr&, const ::Ice::ObjectPtr&);

}

}

namespace pera
{

namespace demo601Client
{

class InvokeException : public ::Ice::UserException
{
public:

    InvokeException() {}
    explicit InvokeException(const ::std::string&);
    virtual ~InvokeException() throw();

    virtual ::std::string ice_name() const;
    virtual InvokeException* ice_clone() const;
    virtual void ice_throw() const;

    ::std::string reason;

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::UserException::__writeImpl;
    using ::Ice::UserException::__readImpl;
    #endif
};

static InvokeException __InvokeException_init;

}

}

namespace Ice
{
template<>
struct StreamableTraits< ::pera::demo601Client::InvokeException>
{
    static const StreamHelperCategory helper = StreamHelperCategoryUserException;
};

}

namespace pera
{

namespace demo601Client
{

class Callback_PeraDemo601ClientService_InvokeMethod_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_PeraDemo601ClientService_InvokeMethod_Base> Callback_PeraDemo601ClientService_InvokeMethodPtr;

}

}

namespace IceProxy
{

namespace pera
{

namespace demo601Client
{

class PeraDemo601ClientService : virtual public ::IceProxy::Ice::Object
{
public:

    ::std::string InvokeMethod(const ::std::string& strMethodName, const ::std::string& strJsonIn)
    {
        return InvokeMethod(strMethodName, strJsonIn, 0);
    }
    ::std::string InvokeMethod(const ::std::string& strMethodName, const ::std::string& strJsonIn, const ::Ice::Context& __ctx)
    {
        return InvokeMethod(strMethodName, strJsonIn, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_InvokeMethod(const ::std::string& strMethodName, const ::std::string& strJsonIn, const ::IceInternal::Function<void (const ::std::string&)>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_InvokeMethod(strMethodName, strJsonIn, 0, response, exception, sent);
    }
    ::Ice::AsyncResultPtr
    begin_InvokeMethod(const ::std::string& strMethodName, const ::std::string& strJsonIn, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_InvokeMethod(strMethodName, strJsonIn, 0, ::Ice::newCallback(completed, sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_InvokeMethod(const ::std::string& strMethodName, const ::std::string& strJsonIn, const ::Ice::Context& ctx, const ::IceInternal::Function<void (const ::std::string&)>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_InvokeMethod(strMethodName, strJsonIn, &ctx, response, exception, sent);
    }
    ::Ice::AsyncResultPtr
    begin_InvokeMethod(const ::std::string& strMethodName, const ::std::string& strJsonIn, const ::Ice::Context& ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_InvokeMethod(strMethodName, strJsonIn, &ctx, ::Ice::newCallback(completed, sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_InvokeMethod(const ::std::string& strMethodName, const ::std::string& strJsonIn, const ::Ice::Context* ctx, const ::IceInternal::Function<void (const ::std::string&)>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception, const ::IceInternal::Function<void (bool)>& sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (const ::std::string&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::pera::demo601Client::PeraDemo601ClientServicePrx __proxy = ::pera::demo601Client::PeraDemo601ClientServicePrx::uncheckedCast(__result->getProxy());
                ::std::string __ret;
                try
                {
                    __ret = __proxy->end_InvokeMethod(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (const ::std::string&)> _response;
        };
        return begin_InvokeMethod(strMethodName, strJsonIn, ctx, new Cpp11CB(response, exception, sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_InvokeMethod(const ::std::string& strMethodName, const ::std::string& strJsonIn)
    {
        return begin_InvokeMethod(strMethodName, strJsonIn, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_InvokeMethod(const ::std::string& strMethodName, const ::std::string& strJsonIn, const ::Ice::Context& __ctx)
    {
        return begin_InvokeMethod(strMethodName, strJsonIn, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_InvokeMethod(const ::std::string& strMethodName, const ::std::string& strJsonIn, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_InvokeMethod(strMethodName, strJsonIn, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_InvokeMethod(const ::std::string& strMethodName, const ::std::string& strJsonIn, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_InvokeMethod(strMethodName, strJsonIn, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_InvokeMethod(const ::std::string& strMethodName, const ::std::string& strJsonIn, const ::pera::demo601Client::Callback_PeraDemo601ClientService_InvokeMethodPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_InvokeMethod(strMethodName, strJsonIn, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_InvokeMethod(const ::std::string& strMethodName, const ::std::string& strJsonIn, const ::Ice::Context& __ctx, const ::pera::demo601Client::Callback_PeraDemo601ClientService_InvokeMethodPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_InvokeMethod(strMethodName, strJsonIn, &__ctx, __del, __cookie);
    }

    ::std::string end_InvokeMethod(const ::Ice::AsyncResultPtr&);
    
private:

    ::std::string InvokeMethod(const ::std::string&, const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_InvokeMethod(const ::std::string&, const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<PeraDemo601ClientService> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<PeraDemo601ClientService*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<PeraDemo601ClientService> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<PeraDemo601ClientService*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<PeraDemo601ClientService> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<PeraDemo601ClientService*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<PeraDemo601ClientService> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<PeraDemo601ClientService*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<PeraDemo601ClientService> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<PeraDemo601ClientService*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<PeraDemo601ClientService> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<PeraDemo601ClientService*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<PeraDemo601ClientService> ice_secure(bool __secure) const
    {
        return dynamic_cast<PeraDemo601ClientService*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<PeraDemo601ClientService> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<PeraDemo601ClientService*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<PeraDemo601ClientService> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<PeraDemo601ClientService*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<PeraDemo601ClientService> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<PeraDemo601ClientService*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<PeraDemo601ClientService> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<PeraDemo601ClientService*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<PeraDemo601ClientService> ice_twoway() const
    {
        return dynamic_cast<PeraDemo601ClientService*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<PeraDemo601ClientService> ice_oneway() const
    {
        return dynamic_cast<PeraDemo601ClientService*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<PeraDemo601ClientService> ice_batchOneway() const
    {
        return dynamic_cast<PeraDemo601ClientService*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<PeraDemo601ClientService> ice_datagram() const
    {
        return dynamic_cast<PeraDemo601ClientService*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<PeraDemo601ClientService> ice_batchDatagram() const
    {
        return dynamic_cast<PeraDemo601ClientService*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<PeraDemo601ClientService> ice_compress(bool __compress) const
    {
        return dynamic_cast<PeraDemo601ClientService*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<PeraDemo601ClientService> ice_timeout(int __timeout) const
    {
        return dynamic_cast<PeraDemo601ClientService*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<PeraDemo601ClientService> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<PeraDemo601ClientService*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<PeraDemo601ClientService> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<PeraDemo601ClientService*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

}

namespace IceDelegate
{

namespace pera
{

namespace demo601Client
{

class PeraDemo601ClientService : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual ::std::string InvokeMethod(const ::std::string&, const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

}

}

}

namespace IceDelegateM
{

namespace pera
{

namespace demo601Client
{

class PeraDemo601ClientService : virtual public ::IceDelegate::pera::demo601Client::PeraDemo601ClientService,
                                 virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual ::std::string InvokeMethod(const ::std::string&, const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

}

namespace IceDelegateD
{

namespace pera
{

namespace demo601Client
{

class PeraDemo601ClientService : virtual public ::IceDelegate::pera::demo601Client::PeraDemo601ClientService,
                                 virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual ::std::string InvokeMethod(const ::std::string&, const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

}

namespace pera
{

namespace demo601Client
{

class PeraDemo601ClientService : virtual public ::Ice::Object
{
public:

    typedef PeraDemo601ClientServicePrx ProxyType;
    typedef PeraDemo601ClientServicePtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual ::std::string InvokeMethod(const ::std::string&, const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___InvokeMethod(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const PeraDemo601ClientService& l, const PeraDemo601ClientService& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const PeraDemo601ClientService& l, const PeraDemo601ClientService& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

}

namespace pera
{

namespace demo601Client
{

template<class T>
class CallbackNC_PeraDemo601ClientService_InvokeMethod : public Callback_PeraDemo601ClientService_InvokeMethod_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::std::string&);

    CallbackNC_PeraDemo601ClientService_InvokeMethod(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::pera::demo601Client::PeraDemo601ClientServicePrx __proxy = ::pera::demo601Client::PeraDemo601ClientServicePrx::uncheckedCast(__result->getProxy());
        ::std::string __ret;
        try
        {
            __ret = __proxy->end_InvokeMethod(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_PeraDemo601ClientService_InvokeMethodPtr
newCallback_PeraDemo601ClientService_InvokeMethod(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_PeraDemo601ClientService_InvokeMethod<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_PeraDemo601ClientService_InvokeMethodPtr
newCallback_PeraDemo601ClientService_InvokeMethod(T* instance, void (T::*cb)(const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_PeraDemo601ClientService_InvokeMethod<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_PeraDemo601ClientService_InvokeMethod : public Callback_PeraDemo601ClientService_InvokeMethod_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::std::string&, const CT&);

    Callback_PeraDemo601ClientService_InvokeMethod(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::pera::demo601Client::PeraDemo601ClientServicePrx __proxy = ::pera::demo601Client::PeraDemo601ClientServicePrx::uncheckedCast(__result->getProxy());
        ::std::string __ret;
        try
        {
            __ret = __proxy->end_InvokeMethod(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_PeraDemo601ClientService_InvokeMethodPtr
newCallback_PeraDemo601ClientService_InvokeMethod(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_PeraDemo601ClientService_InvokeMethod<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_PeraDemo601ClientService_InvokeMethodPtr
newCallback_PeraDemo601ClientService_InvokeMethod(T* instance, void (T::*cb)(const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_PeraDemo601ClientService_InvokeMethod<T, CT>(instance, cb, excb, sentcb);
}

}

}

#endif
