// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `Pera601DemoServerIce.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//
#define ICE_STATIC_LIBS
#include <Pera601DemoServerIce.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <Ice/Object.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

namespace
{

const ::std::string __pera__Demo601Server__PeraDemo601ServerService__InvokeMethod_name = "InvokeMethod";

}

}

namespace
{

const char* __pera__Demo601Server__InvokeException_name = "pera::Demo601Server::InvokeException";

struct __F__pera__Demo601Server__InvokeException : public ::IceInternal::UserExceptionFactory
{
    virtual void
    createAndThrow(const ::std::string&)
    {
        throw ::pera::Demo601Server::InvokeException();
    }
};

class __F__pera__Demo601Server__InvokeException__Init
{
public:

    __F__pera__Demo601Server__InvokeException__Init()
    {
        ::IceInternal::factoryTable->addExceptionFactory("::pera::Demo601Server::InvokeException", new __F__pera__Demo601Server__InvokeException);
    }

    ~__F__pera__Demo601Server__InvokeException__Init()
    {
        ::IceInternal::factoryTable->removeExceptionFactory("::pera::Demo601Server::InvokeException");
    }
};

const __F__pera__Demo601Server__InvokeException__Init __F__pera__Demo601Server__InvokeException__i;

}

pera::Demo601Server::InvokeException::InvokeException(const ::std::string& __ice_reason) :
    ::Ice::UserException(),
    reason(__ice_reason)
{
}

pera::Demo601Server::InvokeException::~InvokeException() throw()
{
}

::std::string
pera::Demo601Server::InvokeException::ice_name() const
{
    return __pera__Demo601Server__InvokeException_name;
}

pera::Demo601Server::InvokeException*
pera::Demo601Server::InvokeException::ice_clone() const
{
    return new InvokeException(*this);
}

void
pera::Demo601Server::InvokeException::ice_throw() const
{
    throw *this;
}

void
pera::Demo601Server::InvokeException::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice("::pera::Demo601Server::InvokeException", -1, true);
    __os->write(reason);
    __os->endWriteSlice();
}

void
pera::Demo601Server::InvokeException::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->read(reason);
    __is->endReadSlice();
}

namespace Ice
{
}
::IceProxy::Ice::Object* ::IceProxy::pera::Demo601Server::upCast(::IceProxy::pera::Demo601Server::PeraDemo601ServerService* p) { return p; }

void
::IceProxy::pera::Demo601Server::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::pera::Demo601Server::PeraDemo601ServerService>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::pera::Demo601Server::PeraDemo601ServerService;
        v->__copyFrom(proxy);
    }
}

::std::string
IceProxy::pera::Demo601Server::PeraDemo601ServerService::InvokeMethod(const ::std::string& methodName, const ::std::string& strJsonIn, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __pera__Demo601Server__PeraDemo601ServerService__InvokeMethod_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__pera__Demo601Server__PeraDemo601ServerService__InvokeMethod_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::pera::Demo601Server::PeraDemo601ServerService* __del = dynamic_cast< ::IceDelegate::pera::Demo601Server::PeraDemo601ServerService*>(__delBase.get());
            return __del->InvokeMethod(methodName, strJsonIn, __ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::pera::Demo601Server::PeraDemo601ServerService::begin_InvokeMethod(const ::std::string& methodName, const ::std::string& strJsonIn, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__pera__Demo601Server__PeraDemo601ServerService__InvokeMethod_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __pera__Demo601Server__PeraDemo601ServerService__InvokeMethod_name, __del, __cookie);
    try
    {
        __result->__prepare(__pera__Demo601Server__PeraDemo601ServerService__InvokeMethod_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(methodName);
        __os->write(strJsonIn);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

::std::string
IceProxy::pera::Demo601Server::PeraDemo601ServerService::end_InvokeMethod(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __pera__Demo601Server__PeraDemo601ServerService__InvokeMethod_name);
    ::std::string __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::pera::Demo601Server::InvokeException&)
            {
                throw;
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

const ::std::string&
IceProxy::pera::Demo601Server::PeraDemo601ServerService::ice_staticId()
{
    return ::pera::Demo601Server::PeraDemo601ServerService::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::pera::Demo601Server::PeraDemo601ServerService::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::pera::Demo601Server::PeraDemo601ServerService);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::pera::Demo601Server::PeraDemo601ServerService::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::pera::Demo601Server::PeraDemo601ServerService);
}

::IceProxy::Ice::Object*
IceProxy::pera::Demo601Server::PeraDemo601ServerService::__newInstance() const
{
    return new PeraDemo601ServerService;
}

::std::string
IceDelegateM::pera::Demo601Server::PeraDemo601ServerService::InvokeMethod(const ::std::string& methodName, const ::std::string& strJsonIn, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __pera__Demo601Server__PeraDemo601ServerService__InvokeMethod_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(methodName);
        __os->write(strJsonIn);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    ::std::string __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::pera::Demo601Server::InvokeException&)
            {
                throw;
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

::std::string
IceDelegateD::pera::Demo601Server::PeraDemo601ServerService::InvokeMethod(const ::std::string& methodName, const ::std::string& strJsonIn, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::std::string& __result, const ::std::string& __p_methodName, const ::std::string& __p_strJsonIn, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_methodName(__p_methodName),
            _m_strJsonIn(__p_strJsonIn)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::pera::Demo601Server::PeraDemo601ServerService* servant = dynamic_cast< ::pera::Demo601Server::PeraDemo601ServerService*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            try
            {
                _result = servant->InvokeMethod(_m_methodName, _m_strJsonIn, _current);
                return ::Ice::DispatchOK;
            }
            catch(const ::Ice::UserException& __ex)
            {
                setUserException(__ex);
                return ::Ice::DispatchUserException;
            }
        }
        
    private:
        
        ::std::string& _result;
        const ::std::string& _m_methodName;
        const ::std::string& _m_strJsonIn;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __pera__Demo601Server__PeraDemo601ServerService__InvokeMethod_name, ::Ice::Normal, __context);
    ::std::string __result;
    try
    {
        _DirectI __direct(__result, methodName, strJsonIn, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::pera::Demo601Server::InvokeException&)
    {
        throw;
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

::Ice::Object* pera::Demo601Server::upCast(::pera::Demo601Server::PeraDemo601ServerService* p) { return p; }

namespace
{
const ::std::string __pera__Demo601Server__PeraDemo601ServerService_ids[2] =
{
    "::Ice::Object",
    "::pera::Demo601Server::PeraDemo601ServerService"
};

}

bool
pera::Demo601Server::PeraDemo601ServerService::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__pera__Demo601Server__PeraDemo601ServerService_ids, __pera__Demo601Server__PeraDemo601ServerService_ids + 2, _s);
}

::std::vector< ::std::string>
pera::Demo601Server::PeraDemo601ServerService::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__pera__Demo601Server__PeraDemo601ServerService_ids[0], &__pera__Demo601Server__PeraDemo601ServerService_ids[2]);
}

const ::std::string&
pera::Demo601Server::PeraDemo601ServerService::ice_id(const ::Ice::Current&) const
{
    return __pera__Demo601Server__PeraDemo601ServerService_ids[1];
}

const ::std::string&
pera::Demo601Server::PeraDemo601ServerService::ice_staticId()
{
    return __pera__Demo601Server__PeraDemo601ServerService_ids[1];
}

::Ice::DispatchStatus
pera::Demo601Server::PeraDemo601ServerService::___InvokeMethod(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::std::string methodName;
    ::std::string strJsonIn;
    __is->read(methodName);
    __is->read(strJsonIn);
    __inS.endReadParams();
    try
    {
        ::std::string __ret = InvokeMethod(methodName, strJsonIn, __current);
        ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
        __os->write(__ret);
        __inS.__endWriteParams(true);
        return ::Ice::DispatchOK;
    }
    catch(const ::pera::Demo601Server::InvokeException& __ex)
    {
        __inS.__writeUserException(__ex, ::Ice::DefaultFormat);
    }
    return ::Ice::DispatchUserException;
}

namespace
{
const ::std::string __pera__Demo601Server__PeraDemo601ServerService_all[] =
{
    "InvokeMethod",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

::Ice::DispatchStatus
pera::Demo601Server::PeraDemo601ServerService::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__pera__Demo601Server__PeraDemo601ServerService_all, __pera__Demo601Server__PeraDemo601ServerService_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __pera__Demo601Server__PeraDemo601ServerService_all)
    {
        case 0:
        {
            return ___InvokeMethod(in, current);
        }
        case 1:
        {
            return ___ice_id(in, current);
        }
        case 2:
        {
            return ___ice_ids(in, current);
        }
        case 3:
        {
            return ___ice_isA(in, current);
        }
        case 4:
        {
            return ___ice_ping(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
pera::Demo601Server::PeraDemo601ServerService::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
pera::Demo601Server::PeraDemo601ServerService::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
pera::Demo601Server::__patch(PeraDemo601ServerServicePtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::pera::Demo601Server::PeraDemo601ServerServicePtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::pera::Demo601Server::PeraDemo601ServerService::ice_staticId(), v);
    }
}
